# dotnet core
# Build, test and publish to ci-feed/nuget.org
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- develop

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  bConfig: 'Release'

steps:
- script: dotnet build -c $(bConfig)
  displayName: Build

- script: dotnet test -c $(bConfig) --no-build --logger trx
  displayName: Test

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
  displayName: Publish test results

- script: dotnet pack -c $(bConfig) --no-build -o '$(Build.ArtifactStagingDirectory)/packages'
  displayName: Create package

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/packages'
    artifactName: packages
    artifactType: Container
  displayName: Publish nuget artifacts
