# dotnet core
# Build, test and publish to ci-feed/nuget.org
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- develop

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  bConfig: 'Release'

steps:
- script: dotnet build -c $(bConfig)
  displayName: Build

- script: dotnet test -c $(bConfig) --no-build --logger trx
  displayName: Test

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
  displayName: Publish test results

- script: dotnet pack -c $(bConfig) --no-build -o '$(Build.ArtifactStagingDirectory)'
  displayName: Create package

- task: NuGetCommand@2
  inputs:
    command: 'push'
    nuGetFeedType: 'internal'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    publishVstsFeed: 'Dev'
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Internal NuGet publish (Dev@LokenData)


- task: NuGetCommand@2
  inputs:
    command: 'push'
    nuGetFeedType: 'external'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    publishFeedCredentials: 'Loken@NuGet.org'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: External NuGet publish (Loken@NuGet.org)
  